export const ActionType = {
  // Modal
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  // Project
  PUSH_PROJECT: "PUSH_PROJECT",
  REMOVE_PROJECT: "REMOVE_PROJECT",
  UPDATE_PROJECT: "UPDATE_PROJECT",
  // Projects
  SET_PROJECTS: "SET_PROJECTS",
  // Opened Project
  SET_OPENED_PROJECT: "SET_OPENED_PROJECT",
  // Todo
  PUSH_TODO: "PUSH_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  SET_IN_PROGRESS_TODO: "SET_IN_PROGRESS_TODO",
} as const;
